version: '3.8'

networks:
  openfga:

volumes:
  openfga:
  django:

services:
  web:
    restart: always
    build: .
    container_name: chatbot-web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:4000"
    volumes:
      - django:/data
      - ./model-cache:/model-cache
    ports:
      - "127.0.0.1:4000:4000"
    networks:
      - openfga
    env:
      - SENTENCE_TRANSFORMERS_HOME=/model-cache
    env_file:
      - .env

  openfga:
    restart: always
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    environment:
      - OPENFGA_DATASTORE_ENGINE=sqlite
      - OPENFGA_DATASTORE_URI=file:/home/nonroot/openfga.db
      - OPENFGA_LOG_FORMAT=json
    command: run
    networks:
      - openfga
    user: nonroot
    volumes:
      - openfga:/home/nonroot
    ports:
      - "127.0.0.1:23080:8080"

  migrate:
    image: openfga/openfga:latest
    container_name: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=sqlite
      - OPENFGA_DATASTORE_URI=file:/home/nonroot/openfga.db
    command: migrate --verbose --timeout 5s
    networks:
      - openfga
    user: nonroot
    volumes:
      - openfga:/home/nonroot
